//BOARD ACTIONS
export const CREATE_BOARD = 'CREATE_BOARD';
export const RENAME_BOARD = 'RENAME_BOARD';
export const DELETE_BOARD = 'DELETE_BOARD';

//TASK ACTIONS
export const CREATE_TASK = 'CREATE_TASK';