//BOARD ACTIONS
export const CREATE_BOARD = 'CREATE_BOARD';
export const RENAME_BOARD = 'RENAME_BOARD';
export const DELETE_BOARD = 'DELETE_BOARD';
export const CLEAR_BOARD = 'CLEAR_BOARD';

//TASK ACTIONS
export const CREATE_TASK = 'CREATE_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const TRANSFER_TASK = 'TRANSFER_TASK ';